<a href="https://colab.research.google.com/github/Hari-Priya-18/B6_PFDS_1372/blob/main/Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question-1

In [12]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[4,3,2]])
B=np.array([[9,8,7],[1,2,3],[5,3,4]])
print("Matrix A:\n",A)
print("Matrix B:\n",B)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [4 3 2]]
Matrix B:
 [[9 8 7]
 [1 2 3]
 [5 3 4]]


Addition

In [10]:
add = np.add(A, B)
print("Addition (A + B):\n", add)

Addition (A + B):
 [[10 10 10]
 [ 5  7  9]
 [ 9  6  6]]


Subtraction

In [9]:
sub = np.subtract(A, B)
print("Subtraction (A - B):\n", sub)

Subtraction (A - B):
 [[-8 -6 -4]
 [ 3  3  3]
 [-1  0 -2]]


Question-2

In [11]:
P=np.array([[3,4,5],[2,3,1]])
Q=np.array([[1,2],[3,4],[5,6]])
print("Matrix P:\n",P)
print("Matrix Q:\n",Q)

Matrix P:
 [[3 4 5]
 [2 3 1]]
Matrix Q:
 [[1 2]
 [3 4]
 [5 6]]


Dot Product using np.dot()

In [13]:
dot_product = np.dot(P, Q)
print("Dot Product (P . Q):\n", dot_product)

Dot Product (P . Q):
 [[40 52]
 [16 22]]


Dot Product using the @ operator

In [14]:
dot_product_at = P @ Q
print("Dot Product (P @ Q):\n", dot_product_at)

Dot Product (P @ Q):
 [[40 52]
 [16 22]]
